services:
  next:
    build:
      context: .
      args:
        NODE_USER: node
    env_file: ./.env
    ports:
      - 3000:3000
    volumes:
      - ./src:/usr/src/app
      - no_modules:/usr/src/app/node_modules
    tty: true

volumes:
  no_modules:
